my_name = 'Begzat'
print(my_name)
print(type(my_name))
print(id(my_name))
print(my_name.upper())
print(my_name.lower())
print(my_name.capitalize())
print(my_name.replace('e', 'a'))
print(my_name.replace('z', 's'))
print(my_name.replace('g', 'k'))
print(my_name*3)
print(len(my_name))
print(my_name[0])
print(my_name[-1])
print(my_name[1:4])
print(my_name[::2])
print(my_name[::-1])
print(my_name.startswith('B'))
print(my_name.endswith('t'))
print(my_name.split('g'))
print('z' in my_name)
print('x' not in my_name)
print(my_name.isalpha())
print(my_name.isdigit())
print(my_name.islower())
print(my_name.isupper())
print(my_name.isspace())
print(my_name.find('g'))
print(my_name.count('a'))
print(my_name.index('z'))
print(my_name.center(20, '*'))
print(my_name.ljust(20, '-'))


my_comment = 'Hello, my name is Begzat'
print(len(my_comment))
